# # .circleci/config.yml
# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/node:14
#     steps:
#       - checkout
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Build and Test
#           command: npm start

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only:
#                 - main
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  install_and_start:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start App
          command: npm start

workflows:
  version: 2
  install_and_start_workflow:
    jobs:
      - install_and_start:
          filters:
            branches:
              only: main
